#SPDX-License-Identifier: MIT-0
---
- name: Update /etc/apt/sources.list.aarch64 for ubuntu 22.04 for ARM
  ansible.builtin.copy:
    src: sources.list.aarch64
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
    backup: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "22.04"
    - ansible_facts['architecture'] == "aarch64"
- name: Update apt cache
  ansible.builtin.apt:
   update_cache: yes
- name: Install development environment packages
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - curl
      - wget
      - vim
      - python3
      - python3-pip
      - htop
      - bwm-ng
      - net-tools
      - tmux
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - tzdata
    state: present
    update_cache: yes