---
- name: Initialize ROS2 Humble development environment
  hosts: all
  environment:
    DEBIAN_FRONTEND: noninteractive
    TZ: Asia/Seoul
  roles:
    - role: general.init_dev.upload_ssh_key
    - role: general.init_dev.enable_dev_env
      become: true
    - role: general.init_dev.install_ros2_humble
      become: true
